# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appDate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QTableWidgetItem, QHeaderView

import login1
import report_case
import results_win
import sendCurl
import sign_up1
import configparser
class AppConfig(object):
    user_name = None
    xray_path = None
    user_password = None
    use_debug_values = False
    def __init__(self):
        self.readCfg()

    def readCfg(self):
        from configparser import ConfigParser

        configur = ConfigParser()
        print(configur.read('app_config.ini'))

        print("Sections : ", configur.sections())
        print("Installation Library : ", configur.get('installation', 'library'))
        print("Log Errors debugged ? : ", configur.get('debug', 'user_name'))
        print("Port Server : ", configur.getint('server', 'port'))
        print("Worker Server : ", configur.getint('server', 'nworkers'))
        self.user_name = configur.get('debug', 'user_name')
        self.xray_path = configur.get('debug', 'xray_path')
        self.user_password = configur.get('debug', 'user_password')
        self.use_debug_values = configur.getboolean('debug', 'use_debug_values')

class Ui_MainWindow(object):
    unique_id = None
    selected_row = None
    theAppConfig = AppConfig()

    def setupUi(self, MainWindow, client):
        print(self.theAppConfig.user_name)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 624)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(630, 540, 151, 31))
        self.pushButton_6.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(630, 60, 141, 91))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("books3.png"))
        self.label_12.setObjectName("label_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.hide()
        self.pushButton_5.setGeometry(QtCore.QRect(630, 230, 151, 31))
        self.pushButton_5.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.hide()
        self.pushButton_7.setGeometry(QtCore.QRect(630, 270, 151, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 140, 151, 31))
        self.pushButton.setStyleSheet("background-color: rgb(14, 154, 175);\n"
"color: rgb(255,255,255);\n"
"font-size: 16pt\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 211, 111))
        self.label_2.setStyleSheet("color: rgb(14, 154, 175);\n"
"font-size: 42pt ")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 20, 91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo1.png"))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 110, 361, 31))
        self.label_6.setStyleSheet("color: rgb(0, 209, 255);\n"
"font-size: 20pt \n"
"")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 431, 411))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("xray1.png"))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 230, 131, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("AI2.png"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 320, 231, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("pic_2.png"))
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(630, 180, 151, 31))
        self.pushButton_4.setStyleSheet("\n"
"color: rgb(255,255,255);\n"
"background-color: rgb(140, 140, 140);\n"
"font-size: 16pt\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 190, 151, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 84, 42);\n"
                                        "color: rgb(255,255,255);\n"
                                        "font-size: 16pt\n")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.hide()

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(630, 150, 201, 31))
        self.label_7.setStyleSheet("background-color: rgb(54,54,54);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 240, 551, 321))
        self.tableWidget.setStyleSheet("background-color: rgb(197,197,197);\n"
                                       "color: rgb(42, 42, 42);\n"
                                       "font-size: 12pt")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_5.raise_()
        self.label_12.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.pushButton_4.raise_()
        self.label_7.raise_()
        self.label_7.hide()
        self.pushButton_6.raise_()

        self.pushButton.raise_()
        self.tableWidget.raise_()

        self.tableWidget.hide()

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.menuHelp.setTearOffEnabled(False)
        self.menuHelp.setToolTipsVisible(False)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.Stretch)
        header.setSectionResizeMode(1, QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QHeaderView.ResizeToContents)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(lambda: self.open_login_win(client))
        self.pushButton_4.clicked.connect(lambda: self.open_sign_up_win(client))
        self.pushButton_7.clicked.connect(lambda: self.select_photo(client))
        self.pushButton_5.clicked.connect(lambda: self.open_report_case_win(client))
        self.tableWidget.selectionModel().selectionChanged.connect(self.selected_row)
        self.tableWidget.doubleClicked.connect(lambda: self.double_click_item(client))
        self.pushButton_2.clicked.connect(lambda: self.back_to_home_page())


    def selected_row(self, selected):
        for ix in selected.indexes():
            self.selected_row = ix.row()

    def double_click_item(self, client):
        patient_id = self.tableWidget.item(self.selected_row, 1).text()
        self.dialog = QtWidgets.QDialog()
        self.ui = report_case.Ui_Report_case()
        self.ui.setupUi(self.dialog, client, self, self.unique_id)
        self.ui.turn_into_show_patient_mode(client, patient_id)
        self.dialog.show()

    def open_login_win(self, client):
        self.dialog = QtWidgets.QDialog()
        self.ui = login1.Ui_Login()
        self.ui.setupUi(self.dialog, client, self)
        self.dialog.show()

    def open_sign_up_win(self, client):
        self.dialog = QtWidgets.QDialog()
        self.ui = sign_up1.Ui_Sign_up()
        self.ui.setupUi(self.dialog, client, self)
        self.dialog.show()

    def turn_into_logged_in_mode(self, username, unique_id):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.hide()
        self.pushButton_4.hide()
        self.label_3.hide()
        self.label_4.hide()
        self.label_5.hide()
        self.label_7.show()
        self.label_7.setText(_translate("MainWindow", "Hello " + username + ","))
        self.pushButton_7.show()
        self.pushButton_5.show()
        self.unique_id = unique_id
        self.tableWidget.show()
        self.pushButton_2.show()

    def fill_table(self, client):
        patient_list = client.get_patients_list(self.unique_id)
        table = self.tableWidget
        for row in patient_list:
            row = row.split('#')
            table.insertRow(table.rowCount())
            rowCount = table.rowCount()
            columnCount = table.columnCount()
            for j in range(columnCount):
                table.setItem(rowCount - 1, j, QTableWidgetItem(row[j]))

    def clear_table(self):
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)

    def select_photo(self, client):
        # fname = QFileDialog.getOpenFileName(self,"Open File", "", "All Files (*);;Python Files (*.py)")
        # Dialog.destroy()
        photo_path = self.get_file_name()
        print(photo_path)
        chance = sendCurl.send_curl(photo_path)
        print(chance)
        if chance != '':
            split_chance = chance.split()
            is_pneu = True
            if split_chance[0] == 'normal':
                is_pneu = False
            self.open_results_win(is_pneu)
        # client.send_photo(photo_path)

    def open_results_win(self, is_pneu):
        self.dialog = QtWidgets.QDialog()
        self.ui = results_win.Ui_results_win()
        self.ui.setupUi(self.dialog, is_pneu, False)
        self.dialog.show()
    def get_file_name(self):
        file_filter = 'Data File (*.jpeg)'
        response = QFileDialog.getOpenFileName(
            caption='Select a data file',
            directory=os.getcwd(),
            filter=file_filter,
            initialFilter='jpeg File (*.jpeg)'
        )
        print(response)
        return response[0]

    def open_report_case_win(self, client):
        # self.dialog = QtWidgets.QDialog()
        self.dialog = QtWidgets.QMainWindow()
        self.ui = report_case.Ui_Report_case()
        self.ui.setupUi(self.dialog, client, self, self.unique_id)
        self.dialog.show()

    def back_to_home_page(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.show()
        self.pushButton_4.show()
        self.label_3.show()
        self.label_4.show()
        self.label_5.show()
        self.label_7.hide()
        self.pushButton_7.hide()
        self.pushButton_5.hide()
        self.unique_id = None
        self.tableWidget.hide()
        self.pushButton_2.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("DeTech", "DeTech"))
        self.pushButton_6.setText(_translate("MainWindow", "about DeTECh"))
        self.pushButton_5.setText(_translate("MainWindow", "report a case"))
        self.pushButton_7.setText(_translate("MainWindow", "X-ray detection"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "DeTech"))
        self.label_6.setText(_translate("MainWindow", "Pneumonia detection using AI"))
        self.pushButton_4.setText(_translate("MainWindow", "Sign up"))
        self.label_7.setText(_translate("MainWindow", "Hello "))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "patient name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "date"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.pushButton_2.setText(_translate("MainWindow", "Log out"))
